import React from 'react'

import { DataType, Table } from 'ka-table'
import { FilteringMode } from 'ka-table/enums'
import { PagingPosition, SortingMode } from 'ka-table/enums'
const dataArray: any[] = [
  {
    no: 1,
    busName: 'CTP',
    time: '5:00 AM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 2,
    busName: '5 (A)',
    time: '5:10 AM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'C.Mutlur',
  },
  {
    no: 3,
    busName: '288 ECR',
    time: '5:15 AM',
    from: 'Chidambaram',
    to: 'Chennai',
    route: 'Parangipettai',
  },
  {
    no: 4,
    busName: '5 (D)',
    time: '5:20 AM',
    from: 'Chidambaram',
    to: 'Ayyampettai',
    route: 'Buvanagiri',
  },
  {
    no: 5,
    busName: 'Lakshmi Narayanan LNC',
    time: '5:40 AM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 6,
    busName: '5 A (A)',
    time: '5:40 AM',
    from: 'Chidambaram',
    to: 'Vathiyapalli',
    route: 'Buvanagiri',
  },
  {
    no: 7,
    busName: '5 (B)',
    time: '6:00 AM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'Buvanagiri',
  },
  {
    no: 8,
    busName: '5 B (B)',
    time: '6:45 AM',
    from: 'Chidambaram',
    to: 'SamiyarPettai',
    route: 'Buvanagiri',
  },
  {
    no: 9,
    busName: '5 (A)',
    time: '7:10 AM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'C.Mutlur',
  },
  {
    no: 10,
    busName: '5 (C)',
    time: '7:10 AM',
    from: 'Annamalai nagar',
    to: 'Puthukuppam',
    route: 'Buvanagiri',
  },
  {
    no: 11,
    busName: 'Sri krishna',
    time: '7:30 AM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 12,
    busName: 'Vigneshwarah',
    time: '7:40 AM',
    from: 'Chidambaram',
    to: 'Mettupalayam',
    route: 'Parangipettai',
  },
  {
    no: 13,
    busName: '5 (B)',
    time: '8:00 AM',
    from: 'Chidambaram',
    to: 'Marine Biology',
    route: 'Buvanagiri',
  },
  {
    no: 14,
    busName: '239',
    time: '8:15 AM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 15,
    busName: '5 A (A)',
    time: '8:30 AM',
    from: 'Chidambaram',
    to: 'Vathiyapalli',
    route: 'Buvanagiri',
  },
  {
    no: 16,
    busName: 'CTP',
    time: '8:45 AM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 17,
    busName: '5 (D)',
    time: '8:50 AM',
    from: 'Chidambaram',
    to: 'Puthukuppam',
    route: 'Buvanagiri',
  },
  {
    no: 18,
    busName: '5 (A)',
    time: '8:55 AM',
    from: 'Annamalai nagar',
    to: 'Marine Biology',
    route: 'C.Mutlur',
  },
  {
    no: 19,
    busName: 'Sushmitha',
    time: '9:10 AM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 20,
    busName: 'Sri Senthil Kumar',
    time: '9:20 AM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 21,
    busName: '5 B (B)',
    time: '9:25 AM',
    from: 'Chidambaram',
    to: 'SamiyarPettai',
    route: 'Buvanagiri',
  },
  {
    no: 22,
    busName: '17',
    time: '9:50 AM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'C.Mutlur',
  },
  {
    no: 23,
    busName: '5 (B)',
    time: '10:00 AM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'Buvanagiri',
  },
  {
    no: 24,
    busName: 'VRM Iniya SambathKumar',
    time: '10:15 AM',
    from: 'Chidambaram',
    to: 'Virudhachalam',
    route: 'Parangipettai',
  },
  {
    no: 25,
    busName: '5 A (A)',
    time: '10:30 AM',
    from: 'Chidambaram',
    to: 'Vathiyapalli',
    route: 'Buvanagiri',
  },
  {
    no: 26,
    busName: '5 (C)',
    time: '10:30 AM',
    from: 'Annamalai nagar',
    to: 'Annangkovil',
    route: 'Buvanagiri',
  },
  {
    no: 27,
    busName: 'NT',
    time: '10:55 AM',
    from: 'Chidambaram',
    to: 'Puducherry',
    route: 'Parangipettai',
  },
  {
    no: 28,
    busName: '5 (A)',
    time: '11:00 AM',
    from: 'Annamalai nagar',
    to: 'Parangipettai',
    route: 'C.Mutlur',
  },
  {
    no: 29,
    busName: 'Saibaba',
    time: '11:15 AM',
    from: 'Chidambaram',
    to: 'Puducherry',
    route: 'Parangipettai',
  },
  {
    no: 30,
    busName: '5 (D)',
    time: '11:25 AM',
    from: 'Chidambaram',
    to: 'Madavapallam',
    route: 'Buvanagiri',
  },
  {
    no: 31,
    busName: '43',
    time: '11:40 AM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'Buvanagiri',
  },
  {
    no: 32,
    busName: '5 (B)',
    time: '12:00 PM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'Buvanagiri',
  },
  {
    no: 33,
    busName: '6',
    time: '12:20 PM',
    from: 'Chidambaram',
    to: 'SamiyarPettai',
    route: 'Buvanagiri',
  },
  {
    no: 34,
    busName: 'Jaya Krishna',
    time: '12:50 PM',
    from: 'Chidambaram',
    to: 'C.Pudhukuppam',
    route: 'Buvanagiri',
  },
  {
    no: 35,
    busName: '5 (A)',
    time: '12:55 PM',
    from: 'Annamalai nagar',
    to: 'Parangipettai',
    route: 'C.Mutlur',
  },
  {
    no: 36,
    busName: '5 B (B)',
    time: '1:30 PM',
    from: 'Chidambaram',
    to: 'SamiyarPettai',
    route: 'Buvanagiri',
  },
  {
    no: 37,
    busName: '5 A (A)',
    time: '1:40 PM',
    from: 'Chidambaram',
    to: 'Vathiyapalli',
    route: 'Buvanagiri',
  },
  {
    no: 38,
    busName: 'CTP',
    time: '1:45 PM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'Buvanagiri',
  },
  {
    no: 39,
    busName: '5 (C)',
    time: '1:45 PM',
    from: 'Chidambaram',
    to: 'Puthukuppam',
    route: 'Buvanagiri',
  },
  {
    no: 40,
    busName: '5 (B)',
    time: '2:00 PM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'Buvanagiri',
  },
  {
    no: 41,
    busName: '5 (D)',
    time: '2:20 PM',
    from: 'Chidambaram',
    to: 'Madavapallam',
    route: 'Buvanagiri',
  },
  {
    no: 42,
    busName: 'Sri krishna',
    time: '2:30 PM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 43,
    busName: '5 A (A)',
    time: '2:50 PM',
    from: 'Chidambaram',
    to: 'Vathiyapalli',
    route: 'Buvanagiri',
  },
  {
    no: 44,
    busName: '5 (A)',
    time: '2:55 PM',
    from: 'Annamalai nagar',
    to: 'Marine Biology',
    route: 'C.Mutlur',
  },
  {
    no: 45,
    busName: 'CTP',
    time: '3:15 PM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 46,
    busName: 'Sri Senthil Kumar',
    time: '3:30 PM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 47,
    busName: '17',
    time: '3:45 PM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'C.Mutlur',
  },
  {
    no: 48,
    busName: '5 (B)',
    time: '4:00 PM',
    from: 'Chidambaram',
    to: 'Marine Biology',
    route: 'Buvanagiri',
  },
  {
    no: 49,
    busName: 'NT',
    time: '4:15 PM',
    from: 'Chidambaram',
    to: 'Puducherry',
    route: 'Parangipettai',
  },
  {
    no: 50,
    busName: '5 B (B)',
    time: '4:25 PM',
    from: 'Chidambaram',
    to: 'SamiyarPettai',
    route: 'Buvanagiri',
  },
  {
    no: 51,
    busName: '5 A (A)',
    time: '4:50 PM',
    from: 'Chidambaram',
    to: 'Vathiyapalli',
    route: 'Buvanagiri',
  },
  {
    no: 52,
    busName: 'Sushmitha',
    time: '5:00 PM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 53,
    busName: '5 (C)',
    time: '5:00 PM',
    from: 'Annamalai nagar',
    to: 'Annangkovil',
    route: 'Buvanagiri',
  },
  {
    no: 54,
    busName: 'VRM Iniya SambathKumar',
    time: '5:00 PM',
    from: 'Chidambaram',
    to: 'Virudhachalam',
    route: 'Parangipettai',
  },
  {
    no: 55,
    busName: 'Saibaba',
    time: '5:20 PM',
    from: 'Chidambaram',
    to: 'Puducherry',
    route: 'Parangipettai',
  },
  {
    no: 56,
    busName: '5 (D)',
    time: '5:35 PM',
    from: 'Chidambaram',
    to: 'Ayyampettai',
    route: 'Buvanagiri',
  },
  {
    no: 57,
    busName: '5 (A)',
    time: '5:50 PM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'C.Mutlur',
  },
  {
    no: 58,
    busName: '5 (B)',
    time: '6:10 PM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'Buvanagiri',
  },
  {
    no: 59,
    busName: 'Jaya Krishna',
    time: '6:20 PM',
    from: 'Chidambaram',
    to: 'C.Pudhukuppam',
    route: 'Buvanagiri',
  },
  {
    no: 60,
    busName: '17',
    time: '6:35 PM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'C.Mutlur',
  },
  {
    no: 61,
    busName: '5 A (A)',
    time: '6:50 PM',
    from: 'Chidambaram',
    to: 'Vathiyapalli',
    route: 'Buvanagiri',
  },
  {
    no: 62,
    busName: '5 B (B)',
    time: '7:10 PM',
    from: 'Chidambaram',
    to: 'SamiyarPettai',
    route: 'Buvanagiri',
  },
  {
    no: 63,
    busName: '5 (C)',
    time: '7:40 PM',
    from: 'Chidambaram',
    to: 'Puthukuppam',
    route: 'Buvanagiri',
  },
  {
    no: 64,
    busName: '5 (A)',
    time: '7:50 PM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'C.Mutlur',
  },
  {
    no: 65,
    busName: 'CTP',
    time: '7:50 PM',
    from: 'Chidambaram',
    to: 'Cuddalore NT',
    route: 'Parangipettai',
  },
  {
    no: 66,
    busName: '5 (B)',
    time: '8:00 PM',
    from: 'Chidambaram',
    to: 'Parangipettai',
    route: 'Buvanagiri',
  },
  {
    no: 67,
    busName: '5 (D)',
    time: '8:30 PM',
    from: 'Chidambaram',
    to: 'Madavapallam',
    route: 'Buvanagiri',
  },
  {
    no: 68,
    busName: 'Jaya Krishna',
    time: '8:35 PM',
    from: 'Chidambaram',
    to: 'C.Pudhukuppam',
    route: 'Buvanagiri',
  },
  {
    no: 69,
    busName: 'Inthumathi',
    time: '9:35 PM',
    from: 'Chidambaram',
    to: 'Puducherry',
    route: 'Parangipettai',
  },
  {
    no: 70,
    busName: '5 B (B)',
    time: '9:55 PM',
    from: 'Chidambaram',
    to: 'SamiyarPettai',
    route: 'Buvanagiri',
  },
  {
    no: 71,
    busName: 'VRM Iniya SambathKumar',
    time: '10:10 PM',
    from: 'Chidambaram',
    to: 'Kurinjipadi',
    route: 'Parangipettai',
  },
  {
    no: 72,
    busName: '6',
    time: '10:30 PM',
    from: 'Chidambaram',
    to: 'SamiyarPettai',
    route: 'Buvanagiri',
  },
  {
    no: 73,
    busName: '5 (C)',
    time: '12:30 AM',
    from: 'Chidambaram',
    to: 'Annangkovil',
    route: 'Buvanagiri',
  },
  {
    no: 74,
    busName: 'NT',
    time: '12:35 PM',
    from: 'Chidambaram',
    to: 'Puducherry',
    route: 'Parangipettai',
  },
]

const PnoToCdm: React.FC = () => {
  return (
    <div className='fixed-column-demo'>
      <Table
        columns={[
          {
            key: 'no',
            title: 'No',
            style: { width: 20 },
            dataType: DataType.Number,
          },
          {
            key: 'busName',
            title: 'Name',
            dataType: DataType.String,
            style: { width: 20 },
          },
          {
            key: 'time',
            title: 'Time',
            style: { width: 20 },
            dataType: DataType.Time,
          },
          {
            key: 'from',
            title: 'From',
            style: { width: 40 },
            dataType: DataType.String,
          },
          {
            key: 'to',
            title: 'To',
            style: { width: 40 },
            dataType: DataType.String,
          },
          {
            key: 'route',
            title: 'Route',
            style: { width: 60 },
            dataType: DataType.String,
          },
        ]}
        data={dataArray}
        filteringMode={FilteringMode.FilterRow}
        // rowKeyField={'busName'}

        format={({ column, value }) => {
          if (column.dataType === DataType.Date) {
            return (
              value &&
              value.toLocaleDateString('en', {
                month: '2-digit',
                day: '2-digit',
                year: 'numeric',
              })
            )
          }
        }}
        sortingMode={SortingMode.Single}
        rowKeyField={'id'}
        paging={{
          enabled: true,
          pageIndex: 0,
          pageSize: 7,
          pageSizes: [5, 10, 15],
          position: PagingPosition.Bottom,
        }}
      />
    </div>
  )
}

export default PnoToCdm
