import React from 'react'

import { DataType, Table } from 'ka-table'
import { FilteringMode } from 'ka-table/enums'
import { PagingPosition } from 'ka-table/enums'
const dataArray: any[] = [
  {
    type: 'Private',
    busName: 'CTP',
    departureTime: '4.25 AM',
    arrivalTime: '5 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 B (B)',
    departureTime: '5.40 AM',
    arrivalTime: '6.40 AM',
    from: 'Samiyar pettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (C)',
    departureTime: '5.45 AM',
    from: 'AnnangKovil',
    to: 'Annamalai Nagar',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (A)',
    departureTime: '6.10 AM',
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'Public',
    busName: '5 A (A)',
    departureTime: '6.30 AM',
    from: 'Vathiyapalli',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (B)',
    departureTime: '6.55 AM',
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'Saibaba',
    departureTime: '7 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: 'CTP',
    departureTime: '7.30 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (D)',
    departureTime: '7.35 AM',
    from: 'Ayyampettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (A)',
    departureTime: '8 AM',
    from: 'Govt.Hospital',
    to: 'Annamalai Nagar',
    route: 'C.Mutlur',
  },
  {
    type: 'private',
    busName: 'Sri Senthil Kumar',
    departureTime: '8.20 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 B (B)',
    departureTime: '8.25 AM',
    from: 'Samiyar pettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'Vigneshwarah',
    departureTime: '8.50 AM',
    from: 'Bus Stand',
    to: 'KattumannarKudi',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (C)',
    departureTime: '8.55 AM',
    from: 'Puthukuppam',
    to: 'Annamalai Nagar',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (B)',
    departureTime: '9 AM',
    from: 'Marine Biology',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'VRM(iniya) Sambathkumar',
    departureTime: '9.25 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 A (A)',
    departureTime: '9.25 AM',
    from: 'Vathiyapalli',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'Inthumathy',
    departureTime: '9.40 AM',
    from: 'Bus Stand',
    to: 'காடரக்கால்',
    route: 'CDM',
  },
  {
    type: 'private',
    busName: 'NT',
    departureTime: '9.45 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (A)',
    departureTime: '9.55 AM',
    from: 'Marine Biology',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'Public',
    busName: '5 (D)',
    departureTime: '10.30 AM',
    from: 'Puthukuppam',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '17',
    departureTime: '10.40 AM',
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'private',
    busName: 'Sri Krishna',
    departureTime: 0.4479166666666667,
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (B)',
    departureTime: 0.4513888888888889,
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 B (B)',
    departureTime: 0.4618055555555556,
    from: 'Samiyar pettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'Sushmitha',
    departureTime: 0.46875,
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 A (A)',
    departureTime: 0.4791666666666667,
    from: 'Vathiyapalli',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'JayaKrishna',
    departureTime: 0.4895833333333333,
    from: 'C.Puthupettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (A)',
    departureTime: 0.5,
    from: 'Govt.Hospital',
    to: 'Annamalai Nagar',
    route: 'C.Mutlur',
  },
  {
    type: 'Public',
    busName: '5 (C)',
    departureTime: 0.5,
    from: 'AnnangKovil',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'Sushmitha',
    departureTime: 0.5173611111111112,
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'Sri SenthilKumar',
    departureTime: 0.5208333333333334,
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '43',
    departureTime: 0.5243055555555556,
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'CTP',
    departureTime: 0.041666666666666664,
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (B)',
    departureTime: 0.04513888888888889,
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (D)',
    departureTime: 0.05555555555555555,
    from: 'MadavaPallam',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 A (A)',
    departureTime: 0.0625,
    from: 'Vathiyapalli',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '6',
    departureTime: 0.0763888888888889,
    from: 'Samiyar pettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (A)',
    departureTime: 0.0798611111111111,
    from: 'Govt.Hospital',
    to: 'Annamalai Nagar',
    route: 'C.Mutlur',
  },
  {
    type: 'private',
    busName: 'CTP',
    departureTime: 0.10416666666666667,
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (B)',
    departureTime: 0.12152777777777778,
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 B (B)',
    departureTime: '3.10 AM',
    from: 'Samiyar pettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (C)',
    departureTime: '3.15 AM',
    from: 'Puthukuppam',
    to: 'Annamalai Nagar',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'NT',
    departureTime: '3.20 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'VRM(iniya) Sambathkumar',
    departureTime: '3.50 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 A (A)',
    departureTime: '3.50 AM',
    from: 'Vathiyapalli',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'Saibaba',
    departureTime: '4.05 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (A)',
    departureTime: '4 AM',
    from: 'Marine Biology',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'Public',
    busName: '288 ECR',
    departureTime: '4.10 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'Public',
    busName: '5 (D)',
    departureTime: '4.30 AM',
    from: 'MadavaPallam',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '17',
    departureTime: '4.35 AM',
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'Public',
    busName: '5 (B)',
    departureTime: '5 AM',
    from: 'Marine Biology',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'JayaKrishna',
    departureTime: '5.20 AM',
    from: 'C.Puthupettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'Sri Krishna',
    departureTime: '5.30 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 A (A)',
    departureTime: '5.45 AM',
    from: 'Vathiyapalli',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '226 A',
    departureTime: '6 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'Public',
    busName: '5 B (B)',
    departureTime: '6.10 AM',
    from: 'Samiyar pettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (C)',
    departureTime: '6.25 AM',
    from: 'AnnangKovil',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'CTP',
    departureTime: '6.30 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (A)',
    departureTime: '6.55 AM',
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'Public',
    busName: '5 (B)',
    departureTime: '7.05 AM',
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (D)',
    departureTime: '7.20 AM',
    from: 'Ayyampettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '17',
    departureTime: '7.25 AM',
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'private',
    busName: 'JayaKrishna',
    departureTime: '7.45 AM',
    from: 'C.Puthupettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 A (A)',
    departureTime: '8 AM',
    from: 'Vathiyapalli',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (A)',
    departureTime: '8.45 AM',
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'C.Mutlur',
  },
  {
    type: 'Public',
    busName: '5 B (B)',
    departureTime: '8.50 AM',
    from: 'Samiyar pettai',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (C)',
    departureTime: '9 AM',
    from: 'Puthukuppam',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'VRM(iniya) Sambathkumar',
    departureTime: '9.10 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'NT',
    departureTime: '9.30 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (B)',
    departureTime: '9.35 AM',
    from: 'Govt.Hospital',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'Public',
    busName: '5 (D)',
    departureTime: '10.30 AM',
    from: 'MadavaPallam',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
  {
    type: 'private',
    busName: 'Lakhsmi Narayanan LNC',
    departureTime: '12.20 AM',
    from: 'Bus Stand',
    to: 'CDM',
    route: 'Bhuvanagiri',
  },
]

const PnoToCdm: React.FC = () => {
  return (
    <div className='fixed-column-demo'>
      <Table
        columns={[
          // {
          //   key: 'type',
          //   title: 'Type',
          //   style: { width: 20 },
          //   dataType: DataType.String,
          // },
          {
            key: 'busName',
            title: 'Bus Name',
            dataType: DataType.String,
            style: { width: 20 },
          },
          {
            key: 'departureTime',
            title: 'Dep Time',
            style: { width: 20 },
            dataType: DataType.Time,
          },
          {
            key: 'arrivalTime',
            title: 'Arrival Time',
            dataType: DataType.Time,
            style: { width: 20 },
          },
          {
            key: 'from',
            title: 'From',
            style: { width: 40 },
            dataType: DataType.String,
          },
          {
            key: 'to',
            title: 'To',
            style: { width: 40 },
            dataType: DataType.String,
          },
          {
            key: 'route',
            title: 'Route',
            style: { width: 60 },
            dataType: DataType.String,
          },
        ]}
        data={dataArray}
        filteringMode={FilteringMode.FilterRow}
        // rowKeyField={'busName'}

        format={({ column, value }) => {
          if (column.dataType === DataType.Date) {
            return (
              value &&
              value.toLocaleDateString('en', {
                month: '2-digit',
                day: '2-digit',
                year: 'numeric',
              })
            )
          }
        }}
        rowKeyField={'id'}
        paging={{
          enabled: true,
          pageIndex: 0,
          pageSize: 7,
          pageSizes: [5, 10, 15],
          position: PagingPosition.Bottom,
        }}
      />
    </div>
  )
}

export default PnoToCdm
