import React from 'react'

import { DataType, Table } from 'ka-table'
import { FilteringMode } from 'ka-table/enums'
import { PagingPosition, SortingMode } from 'ka-table/enums'
const dataArray: any[] = [
  {
    no: 1,
    busName: 'CTP',
    time: '4:25 AM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 2,
    busName: '5 B (B)',
    time: '5:40 AM',
    from: 'Samiyar- pettai',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 3,
    busName: '5 (C)',
    time: '5:45 AM',
    from: 'Annang- kovil',
    to: 'Annamalai Nagar',
    route: 'Buavanagiri',
  },
  {
    no: 4,
    busName: '5 (A)',
    time: '6:10 AM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 5,
    busName: '5 A (A)',
    time: '6:30 AM',
    from: 'Vathiya- palli',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 6,
    busName: 'Saibaba',
    time: '7:00 AM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 7,
    busName: '5 (B)',
    time: '6:55 AM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 8,
    busName: 'CTP',
    time: '7:30 AM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 9,
    busName: '5 (D)',
    time: '7:35 AM',
    from: 'Ayyam- pettai',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 10,
    busName: '5 (A)',
    time: '8:00 AM',
    from: 'Hospital',
    to: 'Annamalai Nagar',
    route: 'C.Mutlur',
  },
  {
    no: 11,
    busName: 'Sri Senthil Kumar',
    time: '8:20 AM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 12,
    busName: '5 B (B)',
    time: '8:25 AM',
    from: 'Samiyar- pettai',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 13,
    busName: 'Vighneshwarah',
    time: '8:50 AM',
    from: 'Bus stand',
    to: 'Kattumannarkudi',
    route: 'Buavanagiri',
  },
  {
    no: 14,
    busName: '5 (C)',
    time: '8:55 AM',
    from: 'Pudhu- kuppam',
    to: 'Annamalai Nagar',
    route: 'Buavanagiri',
  },
  {
    no: 15,
    busName: '5 (B)',
    time: '9:00 AM',
    from: 'Marine Biology',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 16,
    busName: 'VRM Iniya(SambathKumar)',
    time: '9:25 AM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 17,
    busName: '5 A (A)',
    time: '9:25 AM',
    from: 'Vathiya- palli',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 18,
    busName: 'Inthumathi',
    time: '9:40 AM',
    from: 'Bus stand',
    to: 'Karaikkal',
    route: 'Chidam- baram',
  },
  {
    no: 19,
    busName: 'NT',
    time: '9:45 AM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 20,
    busName: '5 (A)',
    time: '9:55 AM',
    from: 'Marine Biology',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 21,
    busName: '5 (D)',
    time: '10:30 AM',
    from: 'Pudhu- kuppam',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 22,
    busName: '17',
    time: '10:40 AM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 23,
    busName: 'Sri Krishna',
    time: '10:45 AM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 24,
    busName: '5 (B)',
    time: '10:50 AM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 25,
    busName: '5 B (B)',
    time: '11:05 AM',
    from: 'Samiyar- pettai',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 26,
    busName: 'Sushmitha',
    time: '11:15 AM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 27,
    busName: '5 A (A)',
    time: '11:30 AM',
    from: 'Vathiya- palli',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 28,
    busName: 'JayaKrishna',
    time: '11:45 AM',
    from: 'C.Pudhu- kuppam',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 29,
    busName: '5 (A)',
    time: '12:00 PM',
    from: 'Hospital',
    to: 'Annamalai Nagar',
    route: 'C.Mutlur',
  },
  {
    no: 30,
    busName: '5 (C)',
    time: '12:00 PM',
    from: 'Annang- kovil',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 31,
    busName: 'Sushmitha',
    time: '12:25 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 32,
    busName: 'Sri Senthil Kumar',
    time: '12:30 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 33,
    busName: '43',
    time: '12:35 PM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 34,
    busName: 'CTP',
    time: '1:00 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 35,
    busName: '5 (B)',
    time: '1:05 PM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 36,
    busName: '5 (D)',
    time: '1:20 PM',
    from: 'Madava- pallam',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 37,
    busName: '5 A (A)',
    time: '1:30 PM',
    from: 'Vathiya- palli',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 38,
    busName: '6',
    time: '1:50 PM',
    from: 'Samiyar- pettai',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 39,
    busName: '5 (A)',
    time: '1:55 PM',
    from: 'Hospital',
    to: 'Annamalai Nagar',
    route: 'C.Mutlur',
  },
  {
    no: 40,
    busName: 'CTP',
    time: '2:30 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 41,
    busName: '5 (B)',
    time: '2:55 PM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 42,
    busName: '5 B (B)',
    time: '3:10 PM',
    from: 'Samiyar- pettai',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 43,
    busName: '5 (C)',
    time: '3:15 PM',
    from: 'Pudhu- kuppam',
    to: 'Annamalai Nagar',
    route: 'Buavanagiri',
  },
  {
    no: 44,
    busName: 'NT',
    time: '3:20 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 45,
    busName: 'VRM Iniya(SambathKumar)',
    time: '3:50 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 46,
    busName: '5 A (A)',
    time: '3:50 PM',
    from: 'Vathiya- palli',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 47,
    busName: 'Saibaba',
    time: '4:05 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 48,
    busName: '5 (A)',
    time: '4:00 PM',
    from: 'Marine Biology',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 49,
    busName: '288 ECR',
    time: '4:10 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 50,
    busName: '5 (D)',
    time: '4:30 PM',
    from: 'Madava- pallam',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 51,
    busName: '17',
    time: '4:35 PM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 52,
    busName: '5 (B)',
    time: '5:00 PM',
    from: 'Marine Biology',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 53,
    busName: 'Jaya Krishna',
    time: '5:20 PM',
    from: 'C.Pudhu- kuppam',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 54,
    busName: 'Sri Krishna',
    time: '5:30 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 55,
    busName: '5 A (A)',
    time: '5:45 PM',
    from: 'Vathiya- palli',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 56,
    busName: '226 A',
    time: '6:00 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 57,
    busName: '5 B (B)',
    time: '6:10 PM',
    from: 'Samiyar- pettai',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 58,
    busName: '5 (C)',
    time: '6:25 PM',
    from: 'Annang- kovil',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 59,
    busName: 'CTP',
    time: '6:30 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 60,
    busName: '5 (A)',
    time: '6:55 PM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 61,
    busName: '5 (B)',
    time: '7:05 PM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 62,
    busName: '5 (D)',
    time: '7:20 PM',
    from: 'Ayyam- pettai',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 63,
    busName: '17',
    time: '7:25 PM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 64,
    busName: 'JayaKrishna',
    time: '7:45 PM',
    from: 'C.Pudhu- kuppam',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 65,
    busName: '5 A (A)',
    time: '8:00 PM',
    from: 'Vathiya- palli',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 66,
    busName: '5 (A)',
    time: '8:45 PM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'C.Mutlur',
  },
  {
    no: 67,
    busName: '5 B (B)',
    time: '8:50 PM',
    from: 'Samiyar- pettai',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 68,
    busName: '5 (C)',
    time: '9:00 PM',
    from: 'Pudhu- kuppam',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 69,
    busName: 'VRM Iniya (SambathKumar)',
    time: '9:10 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 70,
    busName: 'NT',
    time: '9:30 PM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 71,
    busName: '5 (B)',
    time: '9:35 PM',
    from: 'Hospital',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 72,
    busName: '5 (D)',
    time: '10:30 PM',
    from: 'Madava- pallam',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
  {
    no: 73,
    busName: 'Lakhshmi Narayanan LNC',
    time: '12:20 AM',
    from: 'Bus stand',
    to: 'Chidam- baram',
    route: 'Buavanagiri',
  },
]

const PnoToCdm: React.FC = () => {
  return (
    <div className='fixed-column-demo'>
      <Table
        columns={[
          {
            key: 'no',
            title: 'No',
            style: { width: 20 },
            dataType: DataType.Number,
          },
          {
            key: 'busName',
            title: 'Name',
            dataType: DataType.String,
            style: { width: 20 },
          },
          {
            key: 'time',
            title: 'Time',
            style: { width: 20 },
            dataType: DataType.Time,
          },
          {
            key: 'from',
            title: 'From',
            style: { width: 40 },
            dataType: DataType.String,
          },
          {
            key: 'to',
            title: 'To',
            style: { width: 40 },
            dataType: DataType.String,
          },
          {
            key: 'route',
            title: 'Route',
            style: { width: 60 },
            dataType: DataType.String,
          },
        ]}
        data={dataArray}
        filteringMode={FilteringMode.FilterRow}
        // rowKeyField={'busName'}

        format={({ column, value }) => {
          if (column.dataType === DataType.Date) {
            return (
              value &&
              value.toLocaleDateString('en', {
                month: '2-digit',
                day: '2-digit',
                year: 'numeric',
              })
            )
          }
        }}
        sortingMode={SortingMode.Single}
        rowKeyField={'id'}
        paging={{
          enabled: true,
          pageIndex: 0,
          pageSize: 7,
          pageSizes: [5, 10, 15],
          position: PagingPosition.Bottom,
        }}
      />
    </div>
  )
}

export default PnoToCdm
