import React from 'react'

import { DataType, Table } from 'ka-table'
import { FilteringMode } from 'ka-table/enums'
import { PagingPosition, SortingMode } from 'ka-table/enums'
const dataArray: any[] = [
  {
    no: 1,
    busName: '4 (D)',
    time: '4:35 AM',
    from: 'Mudasal odai',
    to: 'Cuddalore NT',
    route: 'Samiyarpettai',
  },
  {
    no: 2,
    busName: '5 (B)',
    time: '5:20 AM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 3,
    busName: '4 (B)',
    time: '5:25 AM',
    from: 'Vathiyapalli',
    to: 'Cuddalore OT',
    route: 'Pudhuchattiram',
  },
  {
    no: 4,
    busName: 'CTP',
    time: '5:30 AM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 5,
    busName: '288 ECR',
    time: '5:40 AM',
    from: 'Bus stand',
    to: 'Chennai',
    route: 'Puducherry',
  },
  {
    no: 6,
    busName: 'Lakhshmi Narayanan LNC',
    time: '6:20 AM',
    from: 'Bus stand',
    to: 'Thindivanam',
    route: 'Cuddalore NT',
  },
  {
    no: 7,
    busName: '4 (A)',
    time: '7:00 AM',
    from: 'Vathiyapalli',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 8,
    busName: '4 (B)',
    time: '7:40 AM',
    from: 'Vathiyapalli',
    to: 'Cuddalore OT',
    route: 'Pudhuchattiram',
  },
  {
    no: 9,
    busName: 'Sri Krishna',
    time: '8:10 AM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 10,
    busName: 'Vighneshwarah',
    time: '8:15 AM',
    from: 'Bus stand',
    to: 'Mettupalayam',
    route: 'Pudhuchattiram',
  },
  {
    no: 11,
    busName: '4 (C)',
    time: '8:15 AM',
    from: 'Salangai Amman Kovil',
    to: 'Cuddalore OT',
    route: 'Samiyarpettai',
  },
  {
    no: 12,
    busName: '239',
    time: '8:40 AM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 13,
    busName: 'CTP',
    time: '9:30 AM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 14,
    busName: 'Sushmitha',
    time: '9:45 AM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 15,
    busName: '4 (B)',
    time: '9:50 AM',
    from: 'Vathiyapalli',
    to: 'Cuddalore OT',
    route: 'Pudhuchattiram',
  },
  {
    no: 16,
    busName: '4 (A)',
    time: '10:00 AM',
    from: 'Vathiyapalli',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 17,
    busName: 'Sri SenthilKumar',
    time: '10:10 AM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 18,
    busName: '4 (C)',
    time: '10:40 AM',
    from: 'Salangai Amman Kovil',
    to: 'Cuddalore OT',
    route: 'Samiyarpettai',
  },
  {
    no: 19,
    busName: '4 (D)',
    time: '10:45 AM',
    from: 'Mudasal odai',
    to: 'Cuddalore NT',
    route: 'Samiyarpettai',
  },
  {
    no: 20,
    busName: '5 (A)',
    time: '11:00 AM',
    from: 'Vathiyapalli',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 21,
    busName: 'NT',
    time: '11:40 AM',
    from: 'Bus stand',
    to: 'Puducherry',
    route: 'Cuddalore',
  },
  {
    no: 22,
    busName: 'SaiBaba',
    time: '12:05 PM',
    from: 'Bus stand',
    to: 'Puducherry',
    route: 'Cuddalore',
  },
  {
    no: 23,
    busName: '4 (B)',
    time: '12:20 PM',
    from: 'Vathiyapalli',
    to: 'Cuddalore OT',
    route: 'Pudhuchattiram',
  },
  {
    no: 24,
    busName: '4 (C)',
    time: '1:10 PM',
    from: 'Salangai Amman Kovil',
    to: 'Cuddalore OT',
    route: 'Samiyarpettai',
  },
  {
    no: 25,
    busName: 'Dhurga',
    time: '1:35 PM',
    from: 'Bus stand',
    to: 'Pandurti',
    route: 'Pudhuchattiram',
  },
  {
    no: 26,
    busName: '4 (A)',
    time: '1:40 PM',
    from: 'Vathiyapalli',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 27,
    busName: '4 (D)',
    time: '2:15 PM',
    from: 'Mudasal odai',
    to: 'Cuddalore NT',
    route: 'Samiyarpettai',
  },
  {
    no: 28,
    busName: '4 (B)',
    time: '3:00 PM',
    from: 'Vathiyapalli',
    to: 'Cuddalore OT',
    route: 'Pudhuchattiram',
  },
  {
    no: 29,
    busName: 'Sri Krishna',
    time: '3:20 PM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 30,
    busName: '4 (C)',
    time: '3:40 PM',
    from: 'Salangai Amman Kovil',
    to: 'Cuddalore OT',
    route: 'Samiyarpettai',
  },
  {
    no: 31,
    busName: 'CTP',
    time: '4:00 PM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 32,
    busName: 'Sri SenthilKumar',
    time: '4:10 PM',
    from: 'Bus stand',
    to: 'Thindivanam',
    route: 'Cuddalore NT',
  },
  {
    no: 33,
    busName: '4 (A)',
    time: '4:30 PM',
    from: 'Vathiyapalli',
    to: 'Pudhuchattiram',
    route: '--',
  },
  {
    no: 34,
    busName: 'NT',
    time: '4:50 PM',
    from: 'Bus stand',
    to: 'Puducherry',
    route: 'Cuddalore',
  },
  {
    no: 35,
    busName: '4 (B)',
    time: '5:10 PM',
    from: 'Vathiyapalli',
    to: 'Cuddalore OT',
    route: 'Pudhuchattiram',
  },
  {
    no: 36,
    busName: '4 (A)',
    time: '5:20 PM',
    from: 'Vathiyapalli',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 37,
    busName: '4 (D)',
    time: '5:50 PM',
    from: 'Mudasal odai',
    to: 'Cuddalore NT',
    route: 'Samiyarpettai',
  },
  {
    no: 38,
    busName: 'Sushmitha',
    time: '5:55 PM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 39,
    busName: 'SaiBaba',
    time: '6:05 PM',
    from: 'Bus stand',
    to: 'Puducherry',
    route: 'Cuddalore',
  },
  {
    no: 40,
    busName: '4 (C)',
    time: '6:20 PM',
    from: 'Salangai Amman Kovil',
    to: 'Cuddalore OT',
    route: 'Samiyarpettai',
  },
  {
    no: 41,
    busName: '4 (B)',
    time: '7:20 PM',
    from: 'Vathiyapalli',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 42,
    busName: '4 (A)',
    time: '7:55 PM',
    from: 'Vathiyapalli',
    to: 'Cuddalore OT',
    route: 'Pudhuchattiram',
  },
  {
    no: 43,
    busName: 'Dhurga',
    time: '8:00 PM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 44,
    busName: 'CTP',
    time: '8:30 PM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 45,
    busName: '4 (C)',
    time: '8:45 PM',
    from: 'Salangai Amman Kovil',
    to: 'Cuddalore NT',
    route: 'Samiyarpettai',
  },
  {
    no: 46,
    busName: '4 (A)',
    time: '10:00 PM',
    from: 'Vathiyapalli',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 47,
    busName: 'Dhurga',
    time: '10:00 PM',
    from: 'Bus stand',
    to: 'Cuddalore NT',
    route: 'Pudhuchattiram',
  },
  {
    no: 48,
    busName: 'Inthumathi',
    time: '10:20 PM',
    from: 'Bus stand',
    to: 'Puducherry',
    route: 'Cuddalore',
  },
  {
    no: 49,
    busName: 'NT',
    time: '1:10 AM',
    from: 'Bus stand',
    to: 'Puducherry',
    route: 'Cuddalore',
  },
]

const PnoToCdm: React.FC = () => {
  return (
    <div className='fixed-column-demo'>
      <Table
        columns={[
          {
            key: 'no',
            title: 'No',
            style: { width: 20 },
            dataType: DataType.Number,
          },
          {
            key: 'busName',
            title: 'Name',
            dataType: DataType.String,
            style: { width: 20 },
          },
          {
            key: 'time',
            title: 'Time',
            style: { width: 20 },
            dataType: DataType.Time,
          },
          {
            key: 'from',
            title: 'From',
            style: { width: 40 },
            dataType: DataType.String,
          },
          {
            key: 'to',
            title: 'To',
            style: { width: 40 },
            dataType: DataType.String,
          },
          {
            key: 'route',
            title: 'Route',
            style: { width: 60 },
            dataType: DataType.String,
          },
        ]}
        data={dataArray}
        filteringMode={FilteringMode.FilterRow}
        // rowKeyField={'busName'}

        format={({ column, value }) => {
          if (column.dataType === DataType.Date) {
            return (
              value &&
              value.toLocaleDateString('en', {
                month: '2-digit',
                day: '2-digit',
                year: 'numeric',
              })
            )
          }
        }}
        sortingMode={SortingMode.Single}
        rowKeyField={'id'}
        paging={{
          enabled: true,
          pageIndex: 0,
          pageSize: 7,
          pageSizes: [5, 10, 15],
          position: PagingPosition.Bottom,
        }}
      />
    </div>
  )
}

export default PnoToCdm
